relays/urls.py
from django.urls import path

from . import views

app_name = 'relays'

urlpatterns = [
    path('', views.index, name='index'),
    path('server/<int:server>', views.server, name='server'),
    path('relays/ajax/server_messages', views.server_messages, name="server_messages"),
]

relays/models.py
import datetime
import logging

from discord import Colour, SyncWebhook
from solo.models import SingletonModel

from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

logger = logging.getLogger(__name__)


class Relays(models.Model):
    """Meta model for app permissions"""

    class Meta:
        managed = False
        default_permissions = ()
        permissions = (
            ('basic_access', 'Can access this app'),
        )


class Server(models.Model):
    """Servers and their ID"""

    class Protocol_Choice(models.TextChoices):
        DISCORD = 'Discord', _('Discord')
        SLACK = 'Slack', _('Slack')
        XMPP = 'XMPP', _('XMPP')

    server = models.PositiveBigIntegerField(primary_key=True)
    name = models.CharField(max_length=100)
    protocol = models.CharField(max_length=10, default=Protocol_Choice.DISCORD,
                                choices=Protocol_Choice.choices)
    users = models.IntegerField(_("Users"), default=0)
    created_at = models.DateTimeField(auto_now=False, auto_now_add=False, blank=True, null=True)
    deleted = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Server'
        verbose_name_plural = 'Servers'

    def __str__(self):
        return f"{self.name}"

    def _last_message(self):
        return Message.objects.filter(
            channel__server=self.server).latest('timestamp')

    @property
    def last_message(self):
        return self._last_message()

    @property
    def last_message_oneday(self) -> bool:
        time_ref = timezone.now() - datetime.timedelta(days=1)

        if (self._last_message().timestamp < time_ref):
            return True
        else:
            return False

    @property
    def last_message_onehour(self) -> bool:
        time_ref = timezone.now() - datetime.timedelta(hours=1)

        if (self._last_message().timestamp < time_ref):
            return True
        else:
            return False

    @property
    def message_count(self):
        return Message.objects.filter(channel__server=self.server).count()


class User(models.Model):
    id = models.PositiveBigIntegerField(_("User ID"), primary_key=True)
    name = models.CharField(_("Username"), max_length=100, blank=True)
    bot = models.BooleanField(_("Is Bot User?"), default=False)
    created_at = models.DateTimeField(
        _("Created Timestamp"), auto_now=False, auto_now_add=False, blank=True, null=True)

    class Meta:
        verbose_name = _("User")
        verbose_name_plural = _("Users")

    def __str__(self):
        if self.bot is False:
            return f"{self.name}"
        else:
            return f"BOT: {self.name}"


class AccessToken(models.Model):
    """Access Token"""

    token = models.CharField(max_length=256)
    servers = models.ManyToManyField(Server, blank=True)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL, blank=True, null=True)

    appear_offline = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.token}"

    class Meta:
        verbose_name = 'Access Token'
        verbose_name_plural = 'Access Tokens'


class Channel(models.Model):
    """Channel IDs, Names and the Server they belong to"""
    class Channel_Type(models.TextChoices):
        # Thread
        THREAD = 'T', _('Thread')
        # GuildChannel
        TEXTCHANNEL = 'TC', _('GuildChannel.TextChannel')
        FORUMCHANNEL = 'FC', _('GuildChannel.ForumChannel')
        VOICECHANNEL = 'VC', _('GuildChannel.VoiceChannel')
        CATEGORYCHANNEL = 'CC', _('GuildChannel.ForumChannel')
        STAGECHANNEL = 'SC', _('GuildChannel.StageChannel')
        # PrivateChannel0
        DMCHANNEL = 'DM', _('PrivateChannel.DMChannel')
        GROUPCHANNEL = 'GM', _('PrivateChannel.GroupChannel')

    server = models.ForeignKey(Server, on_delete=models.CASCADE, blank=True, null=True)
    parent = models.ForeignKey(
        'self', on_delete=models.CASCADE, blank=True, null=True, help_text="Channel in Category, Or Thread", related_name="channel_parent")
    recipients = models.ManyToManyField(User, verbose_name=_("Recipients"), blank=True)
    channel = models.PositiveBigIntegerField(primary_key=True)
    name = models.CharField(max_length=100)
    deleted = models.BooleanField(default=False)
    channel_type = models.CharField(
        max_length=2, choices=Channel_Type.choices, default=Channel_Type.TEXTCHANNEL)
    created_at = models.DateTimeField(auto_now=False, auto_now_add=False, blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    @property
    def channel_as_path(self):
        if self.parent and self.parent.parent:
            return f"[{self.server}]/{self.parent.parent}/{self.parent}/{self}"
        elif self.parent:
            return f"{self.server}/{self.parent}/{self}"
        else:
            return f"{self.server}/{self}"

    @property
    def channel_as_path_noserver(self):
        if self.parent and self.parent.parent:
            return f"[{self.parent.parent}/{self.parent}/{self}"
        elif self.parent:
            return f"{self.parent}/{self}"
        else:
            return f"{self}"

    class Meta:
        verbose_name = 'Channel'
        verbose_name_plural = 'Channels'
        indexes = [
            models.Index(fields=["server", "channel_type"]),
        ]


class Message(models.Model):
    """Message Storage"""
    message = models.PositiveBigIntegerField()
    edit_count = models.IntegerField(_("Edit Count"), default=1)

    channel = models.ForeignKey(Channel, on_delete=models.CASCADE)
    deleted = models.BooleanField(default=False)
    content = models.TextField(help_text="The primary content of a message")
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    mention_everyone = models.BooleanField(_("Message is @everyone"), default=False)

    user = models.ForeignKey(User, verbose_name=_("User"), on_delete=models.CASCADE)
    author_nick = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return f'"{self.message}"'

    @property
    def server(self):
        return self.channel.server

    @property
    def content_extended(self) -> str:
        all_content = []
        try:
            for e in self.embeds.all():
                all_content.append(str(e.content))
        except Exception as e:
            logger.exception(e)
        try:
            for a in self.attachments.all():
                all_content.append(str(a.content))
        except Exception as e:
            logger.exception(e)
        content_extended = "\n".join(all_content)

        return content_extended

    class Meta:
        verbose_name = 'Message'
        verbose_name_plural = 'Messages'
        unique_together = ('message', 'edit_count')
        indexes = [
            models.Index(fields=["message", "channel", ]),
        ]


class MessageEmbed(models.Model):
    content = models.TextField(_("Message Embed to String"))
    message = models.ForeignKey(Message, verbose_name=_("Message"), on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("MessageEmbed")
        verbose_name_plural = _("MessageEmbeds")

    def __str__(self):
        return f'"{self.pk}"'


class MessageAttachment(models.Model):
    id = models.PositiveBigIntegerField(_("Attachment ID"), primary_key=True)
    filename = models.CharField(_("Filename"), max_length=256)
    media_type = models.CharField(_("Media Type"), max_length=50)
    url = models.CharField(_("URL"), max_length=2048)
    message = models.ForeignKey(Message, verbose_name=_("Message"), on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Message Attachment")
        verbose_name_plural = _("Message Attachments")

    def __str__(self):
        return f'{self.filename}'


class Webhook(models.Model):
    """Destinations for Relays"""
    url = models.CharField(max_length=2048)
    name = models.CharField(max_length=256)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = 'Destination Webhook'
        verbose_name_plural = 'Destination Webhooks'

    def send_embed(self, embed):
        webhook = SyncWebhook.from_url(self.url)
        webhook.send(embed=embed, username="AA Relays")


class DestinationAADiscordBot(models.Model):
    """Destination Channels to be passed to AA-Discord
    Bot DON'T set this to hostile channels you potato"""
    class Message_Type(models.TextChoices):
        CHANNEL_MESSAGE = 'CM', _('Channel Message')
        DIRECT_MESSAGE = 'DM', _('Direct Message')

    destination_type = models.CharField(max_length=2,
                                        choices=Message_Type.choices,
                                        default=Message_Type.CHANNEL_MESSAGE)
    destination = models.ForeignKey("aadiscordbot.channels", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.destination}"

    class Meta:
        verbose_name = 'Discord Channel Destination'
        verbose_name_plural = 'Discord Channel Destinations'


class RelayConfiguration(models.Model):
    """In and Out...... Repeat"""
    name = models.CharField(max_length=100)

    source_servers = models.ManyToManyField(Server, blank=True)
    source_server_all = models.BooleanField(default=False)
    source_channels = models.ManyToManyField(Channel, blank=True)
    source_channel_all = models.BooleanField(default=False)

    message_mention = models.BooleanField(default=True)
    message_non_mention = models.BooleanField(default=False)
    message_regex = models.CharField(max_length=10, default=".^", blank=False, null=False)

    relay_event = models.BooleanField(default=True)
    relay_embed = models.BooleanField(default=True)
    relay_private_message = models.BooleanField(default=True, help_text="Not Yet Implemented")

relays/templates/relays/base-bs5.html
{% extends "allianceauth/base-bs5.html" %}
{% load i18n %}
{% load humanize %}
{% load static %}

{% block page_title %}
    {% translate "Relays" %}
{% endblock page_title %}

{% block header_nav_brand %}
    <a class="navbar-brand" href="{% url 'relays:index' %}">{% trans "Relays" %}</a>
{% endblock header_nav_brand %}
{% block header_nav_collapse_left %}
{% endblock header_nav_collapse_left %}

{% block header_nav_collapse_right %}
{% endblock header_nav_collapse_right %}

{% block content %}
{% endblock content %}

relays/templates/relays/base.html
{% extends "allianceauth/base.html" %}
{% load i18n %}
{% load humanize %}
{% load static %}
{% block page_title %}
    {% translate "Relays" %}
{% endblock page_title %}
{% block content %}
    <div class="container-fluid aa-relays">
        <br />
        <nav class="navbar navbar-default">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#relays-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">{% trans "Toggle navigation" %}</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'relays:index' %}">{% trans "Relays" %}</a>
            </div>
            <div class="collapse navbar-collapse" id="relays-navbar-collapse-1"></div>
        </nav>
        {% block details %}
        {% endblock details %}
    </div>
{% endblock content %}

relays/templates/relays/index-bs5.html
{% extends "relays/base-bs5.html" %}
{% load i18n %}
{% load humanize %}
{% block content %}
    <div class="row row-cols-1 row-cols-md-3 row-cols-lg-6 g-2">
        {% for server in servers %}
            <div class="col">
                <div class="card h-100">
                    <div class="card-header">
                        <h5 class="card-title">{{ server.name }}</h5>
                        {% if server.last_message_oneday %}
                            <span class="badge text-bg-danger">{{ server.last_message.timestamp|naturaltime }}</span>
                        {% elif server.last_message_onehour %}
                            <span class="badge text-bg-warning">{{ server.last_message.timestamp|naturaltime }}</span>
                        {% else %}
                            <span class="badge bg-secondary">{{ server.last_message.timestamp|naturaltime }}</span>
                        {% endif %}
                    </div>
                    <div class="card-body">
                        {% trans "Channels" %}:<span class="badge bg-secondary">{{ server.channel_set.count|intcomma }}</span>
                        <br />
                        {% trans "Users" %}:<span class="badge bg-secondaryt">{{ server.users|intcomma }}</span>
                        <br />
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'relays:server' server.server %}"><span class="btn btn-primary" role="button">{% trans "View Messages" %}: <span class="badge bg-secondary">{{ server.message_count|intcomma }}</span></a></span>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock content %}

relays/templates/relays/index.html
{% extends "relays/base.html" %}
{% load i18n %}
{% load humanize %}
{% block details %}
    <div class="panel panel-success col-lg-12 container-fluid">
        <div class="panel-heading">
            <span class="panel-title">{% translate "Relay Servers" %}</span>
        </div>
        <div class="panel-body">
            {% for server in servers %}
                <div class="panel panel-default col-lg-3 col-md-4 col-sm-6 col-xs-12">
                    <div class="panel-heading">
                        <div class="panel-title">
                            {{ server.name }}
                            {% if server.last_message_oneday %}
                                <span class="label label-danger">{{ server.last_message.timestamp|naturaltime }}</span>
                            {% elif server.last_message_onehour %}
                                <span class="label label-warning">{{ server.last_message.timestamp|naturaltime }}</span>
                            {% else %}
                                <span class="label label-default">{{ server.last_message.timestamp|naturaltime }}</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="panel-body">
                        {% trans "Channels" %}:<span class="label label-default">{{ server.channel_set.count|intcomma }}</span><br />
                        {% trans "Users" %}:<span class="label label-default">{{ server.users|intcomma }}</span><br />
                        <a href="{% url 'relays:server' server.server %}"><span class="btn btn-primary" role="button">{% trans "View Messages" %}: <span class="label label-default">{{ server.message_count|intcomma }}</span></a></span>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock details %}
{% block extra_javascript %}
{% endblock extra_javascript %}
{% block extra_css %}
{% endblock extra_css %}
{% block extra_script %}
{% endblock extra_script %}

relays/templates/relays/server-bs5.html
{% extends "relays/base-bs5.html" %}
{% load i18n %}
{% load humanize %}
{% block content %}
    <div class="card card-success col-lg-12 container-fluid">
        <div class="card-header">
            <span class="card-title">{% translate "Server" %}: {{ server.name }}</span>
        </div>
        <div class="card-body">{% include "relays/server_messages.html" %}</div>
    </div>
{% endblock content %}
{% block extra_javascript %}
    {% include "bundles/datatables-js-bs5.html" %}
    {% include "bundles/moment-js.html" with locale=True %}
{% endblock extra_javascript %}

{% block extra_css %}
    {% include "bundles/datatables-css-bs5.html" %}
{% endblock extra_css %}
{% block extra_script %}
    $(document).ready(function(){
    $('#table-server-messages').DataTable({
    "ajax": {
    "url": "{% url 'relays:server_messages' %}",
    "dataSrc": "server_messages",
    "data": {
    "server_id": "{{ server.server }}"
    }
    },
    columns: [
    {
    data: "timestamp"
    },
    {
    data: "channel__name"
    },
    {
    data: "author_nick"
    },
    {
    data: 'content',
    },

    ],
    "order": [[ 2, "asc" ]],
    "processing": true,
    "stateSave": true,
    "stateDuration": 0,
    } );
    });
{% endblock extra_script %}

relays/templates/relays/server.html
{% extends "relays/base.html" %}
{% load i18n %}
{% load humanize %}
{% block details %}
    <div class="panel panel-success col-lg-12 container-fluid">
        <div class="panel-heading">
            <span class="panel-title">{% translate "Server" %}: {{ server.name }} </span>
        </div>
        <div class="panel-body">
            {% include "relays/server_messages.html" %}
        </div>
    </div>
{% endblock details %}
{% block extra_javascript %}
    {% include "bundles/datatables-js.html" %}
    {% include "bundles/moment-js.html" with locale=True %}
{% endblock extra_javascript %}

{% block extra_css %}
    {% include "bundles/datatables-css.html" %}
{% endblock extra_css %}
{% block extra_script %}
    $(document).ready(function(){
        $('#table-server-messages').DataTable({
            "ajax": {
                "url": "{% url 'relays:server_messages' %}",
                "dataSrc": "server_messages",
                "data": {
                    "server_id": "{{ server.server }}"
                }
            },
            columns: [
            {
                data: "timestamp"
            },
            {
                data: "channel__name"
            },
            {
                data: "author_nick"
            },
            {
                data: 'content',
            },

            ],
            "order": [[ 2, "asc" ]],
            "processing": true,
            "stateSave": true,
            "stateDuration": 0,
        } );
    });
{% endblock extra_script %}

relays/templates/relays/server_messages-bs5.html
{% load i18n %}
{% load humanize %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">{% translate "Server Messages" %}</h3>
    </div>
    <div class="panel-body">
        <table class="table table-responsive" id="table-server-messages" style="width: 100%;">>
            <thead>
                <tr>
                    <th class="text-left">{% translate "Sent" %}</th>
                    <th class="text-left">{% translate "Channel" %}</th>
                    <th class="text-left">{% translate "Username" %}</th>
                    <th class="text-left">{% translate "Content" %}</th>

                </tr>
            </thead>
        </table>
    </div>
</div>

relays/templates/relays/server_messages.html
{% load i18n %}
{% load humanize %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">{% translate "Server Messages" %}</h3>
    </div>
    <div class="panel-body">
        <table class="table table-responsive" id="table-server-messages" style="width: 100%;">>
            <thead>
                <tr>
                    <th class="text-left">{% translate "Sent" %}</th>
                    <th class="text-left">{% translate "Channel" %}</th>
                    <th class="text-left">{% translate "Username" %}</th>
                    <th class="text-left">{% translate "Content" %}</th>

                </tr>
            </thead>
        </table>
    </div>
</div>